import type {
  CatalogItem,
  Community,
  DomainId,
  LearnerState,
  Profile,
  Skill,
} from "./types";

export const skills: Skill[] = [
  { id: "python", label: "Python basics", domain: "data-ai" },
  { id: "git", label: "Git basics", domain: "shared" },
  { id: "communication", label: "Technical communication", domain: "shared" },
  { id: "numpy", label: "NumPy basics", domain: "data-ai" },
  { id: "pandas", label: "pandas basics", domain: "data-ai" },
  { id: "ml-foundations", label: "ML foundations", domain: "data-ai" },
  { id: "ml-project", label: "Small ML project", domain: "data-ai" },
  { id: "c-basics", label: "C basics", domain: "robotics" },
  { id: "arduino-basics", label: "Arduino basics", domain: "robotics" },
  { id: "circuits", label: "Circuit basics", domain: "robotics" },
  { id: "sensors", label: "Reading sensors", domain: "robotics" },
  {
    id: "embedded-project",
    label: "Small embedded project",
    domain: "robotics",
  },
];

export const communities: Community[] = [
  {
    id: "data-ai",
    name: "Data & AI Circle",
    shortName: "Data & AI",
    description:
      "A place to explore data, build your first ML project, and find someone to learn with.",
    focus: ["Python", "Data exploration", "First ML projects"],
    color: "violet",
  },
  {
    id: "robotics",
    name: "Robotics & Makers Circle",
    shortName: "Robotics & Makers",
    description:
      "Connect with people exploring circuits, sensors, and hands-on embedded projects.",
    focus: ["Arduino", "Sensors", "Embedded systems"],
    color: "teal",
  },
];

// Opportunities are illustrative. Only official documentation entries have external links.
// Official links checked on 28 September 2026; no availability or certification is implied.
export const catalog: CatalogItem[] = [
  {
    id: "first-ml-project",
    kind: "project",
    title: "Build your first ML project",
    domain: "data-ai",
    description:
      "Build a simple program that learns from data. Work with a peer and ask a mentor to review your results.",
    provider: "STEMBridge practice project",
    format: "online",
    cost: "free",
    skills: ["numpy", "pandas", "ml-foundations", "ml-project"],
    requirements: [
      "python",
      "git",
      "communication",
      "numpy",
      "pandas",
      "ml-foundations",
      "ml-project",
    ],
    tags: ["Beginner", "Portfolio project", "Peer collaboration"],
    isSample: true,
  },
  {
    id: "first-embedded-project",
    kind: "project",
    title: "Make a sensor-powered prototype",
    domain: "robotics",
    description:
      "Build a small device that reads a sensor and displays the result. You’ll need a compatible Arduino board and sensor.",
    provider: "STEMBridge practice project",
    format: "hybrid",
    cost: "hardware-required",
    skills: ["circuits", "sensors", "embedded-project"],
    requirements: [
      "c-basics",
      "arduino-basics",
      "circuits",
      "sensors",
      "embedded-project",
      "git",
      "communication",
    ],
    tags: ["Beginner", "Hands-on", "Hardware required"],
    isSample: true,
  },
  {
    id: "data-for-good-challenge",
    kind: "competition",
    title: "Data for Good: mini challenge",
    domain: "data-ai",
    description:
      "Work in a team to use data to explain a local issue. This sample challenge has no scheduled event or registration.",
    provider: "Sample competition",
    format: "online",
    cost: "free",
    skills: ["pandas", "communication"],
    requirements: ["python", "pandas", "communication"],
    tags: ["Team challenge", "Data storytelling", "Sample listing"],
    isSample: true,
  },
  {
    id: "makers-prototype-challenge",
    kind: "competition",
    title: "Makers prototype challenge",
    domain: "robotics",
    description:
      "Build a sensor-based invention with a small team. This sample challenge needs hardware and has no scheduled event.",
    provider: "Sample competition",
    format: "in-person",
    cost: "hardware-required",
    skills: ["sensors", "embedded-project", "communication"],
    requirements: ["arduino-basics", "circuits", "sensors", "communication"],
    tags: ["Team challenge", "In person", "Sample listing"],
    isSample: true,
  },
  {
    id: "data-exploration-internship",
    kind: "internship",
    title: "Data exploration internship",
    domain: "data-ai",
    description:
      "Clean data and explain what you find in this sample internship brief. There is no live opening or application.",
    provider: "Sample internship",
    format: "online",
    cost: "unknown",
    skills: ["pandas", "numpy", "communication"],
    requirements: ["python", "git", "numpy", "pandas", "communication"],
    tags: ["Data analysis", "Beginner brief", "Sample listing"],
    isSample: true,
  },
  {
    id: "embedded-testing-internship",
    kind: "internship",
    title: "Embedded testing internship",
    domain: "robotics",
    description:
      "Test a small sensor system and record the results. This sample internship has no live opening or application.",
    provider: "Sample internship",
    format: "in-person",
    cost: "unknown",
    skills: ["sensors", "embedded-project", "communication"],
    requirements: ["c-basics", "circuits", "sensors", "git", "communication"],
    tags: ["Embedded systems", "In person", "Sample listing"],
    isSample: true,
  },
  {
    id: "numpy-beginners",
    kind: "resource",
    title: "NumPy: the absolute basics",
    domain: "data-ai",
    description:
      "Learn to work with groups of numbers using NumPy arrays. Follow examples from the official beginner guide.",
    provider: "NumPy documentation",
    format: "online",
    cost: "free",
    skills: ["numpy"],
    requirements: ["python"],
    tags: ["Official documentation", "Arrays", "Beginner"],
    isSample: false,
    sourceUrl: "https://numpy.org/doc/stable/user/absolute_beginners.html",
  },
  {
    id: "pandas-introduction",
    kind: "resource",
    title: "10 minutes to pandas",
    domain: "data-ai",
    description:
      "Learn to view, filter and organise data tables with pandas. Start with the official introductory guide.",
    provider: "pandas documentation",
    format: "online",
    cost: "free",
    skills: ["pandas"],
    requirements: ["python", "numpy"],
    tags: ["Official documentation", "Data tables"],
    isSample: false,
    sourceUrl: "https://pandas.pydata.org/docs/user_guide/10min.html",
  },
  {
    id: "scikit-learn-start",
    kind: "resource",
    title: "Get started with scikit-learn",
    domain: "data-ai",
    description:
      "Learn how to train and test a machine-learning model. Follow the official scikit-learn introduction.",
    provider: "scikit-learn documentation",
    format: "online",
    cost: "free",
    skills: ["ml-foundations"],
    requirements: ["python", "numpy"],
    tags: ["Official documentation", "Model basics"],
    isSample: false,
    sourceUrl: "https://scikit-learn.org/stable/getting_started.html",
  },
  {
    id: "ml-practice-notebook",
    kind: "resource",
    title: "Practice: a tiny classifier",
    domain: "data-ai",
    description:
      "STEMBridge practice exercise: load the built-in iris dataset in scikit-learn, split training and test data, fit one classifier, and explain one limitation in a notebook. Ask a peer to review the explanation.",
    provider: "STEMBridge practice exercise",
    format: "online",
    cost: "free",
    skills: ["ml-project"],
    requirements: ["python", "numpy", "pandas", "ml-foundations"],
    tags: ["Practice brief", "Peer review"],
    isSample: true,
  },
  {
    id: "arduino-examples",
    kind: "resource",
    title: "Arduino built-in examples",
    domain: "robotics",
    description:
      "Try simple Arduino examples, starting with a blinking light. The guide is free; building the examples needs suitable hardware.",
    provider: "Arduino documentation",
    format: "online",
    cost: "free",
    skills: ["arduino-basics"],
    requirements: [],
    tags: ["Official documentation", "Free to read", "Hardware for building"],
    isSample: false,
    sourceUrl: "https://docs.arduino.cc/built-in-examples/",
  },
  {
    id: "circuit-planning-exercise",
    kind: "resource",
    title: "Practice: plan a simple circuit",
    domain: "robotics",
    description:
      "STEMBridge paper exercise: sketch a low-voltage Arduino LED circuit, label the power and ground connections, and explain why an LED needs a current-limiting resistor. Ask a mentor to review the sketch before building.",
    provider: "STEMBridge practice exercise",
    format: "online",
    cost: "free",
    skills: ["circuits"],
    requirements: ["arduino-basics"],
    tags: ["Practice brief", "No hardware needed to plan"],
    isSample: true,
  },
  {
    id: "sensor-practice-build",
    kind: "resource",
    title: "Practice: read and explain a sensor",
    domain: "robotics",
    description:
      "STEMBridge practice exercise: using a compatible low-voltage board and sensor, follow the manufacturer's wiring instructions, print readings, and document how the values change. Check wiring with a mentor before powering the circuit. Hardware is required.",
    provider: "STEMBridge practice exercise",
    format: "online",
    cost: "hardware-required",
    skills: ["sensors", "embedded-project"],
    requirements: ["arduino-basics", "circuits"],
    tags: ["Practice brief", "Hardware required"],
    isSample: true,
  },
  {
    id: "share-your-prototype",
    kind: "resource",
    title: "Practice: share your prototype",
    domain: "robotics",
    description:
      "STEMBridge practice exercise: create a Git repository for your sketch, commit your work, and write a short README covering the idea, wiring, and one limitation. Give a two-minute explanation to a peer.",
    provider: "STEMBridge practice exercise",
    format: "online",
    cost: "free",
    skills: ["git", "communication"],
    requirements: ["arduino-basics"],
    tags: ["Practice brief", "Documentation", "Peer feedback"],
    isSample: true,
  },
];

export const sampleProfiles: Profile[] = [
  {
    id: "sample-mentor-ananya",
    display_name: "Ananya Rao",
    headline: "Helping you start your first ML project",
    bio: "Fictional demo mentor. Offers beginner-friendly feedback on datasets, small model experiments, and explaining results.",
    domain: "data-ai",
    skills: [
      "python",
      "numpy",
      "pandas",
      "ml-foundations",
      "ml-project",
      "communication",
    ],
    role: "mentor",
    support_modes: ["online"],
    help_topics: [
      "First project feedback",
      "ML foundations",
      "Getting started",
    ],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
  {
    id: "sample-mentor-meera",
    display_name: "Meera Shah",
    headline: "Beginner data projects, with in-person support",
    bio: "Fictional demo mentor. Helps beginners explore data tables and talk through small data projects in person.",
    domain: "data-ai",
    skills: ["python", "numpy", "pandas", "ml-foundations", "ml-project"],
    role: "mentor",
    support_modes: ["in-person"],
    help_topics: ["Data exploration", "First project feedback"],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
  {
    id: "sample-peer-zoya",
    display_name: "Zoya Khan",
    headline: "Looking for a partner for my first ML project",
    bio: "Fictional demo peer. Comfortable with beginner Python and Git; learning pandas and interested in working through a small dataset together.",
    domain: "data-ai",
    skills: ["python", "git"],
    role: "learner",
    support_modes: ["online"],
    help_topics: ["Project collaboration", "Study buddy"],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
  {
    id: "sample-mentor-kavya",
    display_name: "Kavya Menon",
    headline: "Help with your first Arduino project",
    bio: "Fictional demo mentor. Offers online guidance with small Arduino builds, sensor readings, and documenting a prototype.",
    domain: "robotics",
    skills: [
      "c-basics",
      "arduino-basics",
      "circuits",
      "sensors",
      "embedded-project",
      "git",
      "communication",
    ],
    role: "mentor",
    support_modes: ["online"],
    help_topics: ["Circuit review", "Sensor projects", "Getting started"],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
  {
    id: "sample-peer-ishita",
    display_name: "Ishita Das",
    headline: "Learning to build a sensor project",
    bio: "Fictional demo peer. Has tried Arduino basics and a simple circuit; looking for an online project partner to learn sensors with.",
    domain: "robotics",
    skills: ["c-basics", "arduino-basics", "circuits"],
    role: "learner",
    support_modes: ["online"],
    help_topics: ["Project collaboration", "Arduino practice"],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
  {
    id: "sample-peer-tara",
    display_name: "Tara Nair",
    headline: "Looking for an in-person circuit study buddy",
    bio: "Fictional demo peer. Interested in in-person circuit practice and explaining small builds with another beginner.",
    domain: "robotics",
    skills: ["arduino-basics", "communication"],
    role: "learner",
    support_modes: ["in-person"],
    help_topics: ["Circuit practice", "Study buddy"],
    discoverable: true,
    open_to_requests: true,
    is_demo: true,
  },
];

export function defaultLearnerState(userId: string): LearnerState {
  return {
    user_id: userId,
    confirmed_skills: [],
    interests: [],
    goal_id: null,
    online_only: false,
    saved_ids: [],
    intro: "",
  };
}

const priyaIntro =
  "I am in first-year CSE. I can write beginner Python, commit and push code with Git, and explain a college project in a short presentation. I want to explore machine learning. I have not used NumPy or pandas and have not built an ML project. I prefer online support.";
const aishaIntro =
  "I am a beginner interested in robotics. I can write simple C programs and have uploaded and explained the Arduino Blink example. I have not wired a circuit or read a sensor, and I have not used Git or presented a project. I want to build my first embedded project.";

export const sampleLearners: { profile: Profile; state: LearnerState }[] = [
  {
    profile: {
      id: "sample-learner-priya",
      display_name: "Priya Sharma",
      headline: "First-year student exploring machine learning",
      bio: priyaIntro,
      domain: "data-ai",
      skills: ["python", "git", "communication"],
      role: "learner",
      support_modes: ["online"],
      help_topics: ["Study buddy", "First ML project"],
      discoverable: true,
      open_to_requests: true,
      is_demo: true,
    },
    state: {
      ...defaultLearnerState("sample-learner-priya"),
      confirmed_skills: ["python", "git", "communication"],
      interests: ["data-ai"],
      goal_id: "first-ml-project",
      online_only: true,
      intro: priyaIntro,
    },
  },
  {
    profile: {
      id: "sample-learner-aisha",
      display_name: "Aisha Thomas",
      headline: "Learning robotics, one project at a time",
      bio: aishaIntro,
      domain: "robotics",
      skills: ["c-basics", "arduino-basics"],
      role: "learner",
      support_modes: ["online", "in-person"],
      help_topics: ["Study buddy", "First sensor project"],
      discoverable: true,
      open_to_requests: true,
      is_demo: true,
    },
    state: {
      ...defaultLearnerState("sample-learner-aisha"),
      confirmed_skills: ["c-basics", "arduino-basics"],
      interests: ["robotics"],
      goal_id: "first-embedded-project",
      intro: aishaIntro,
    },
  },
];

export function getSkillLabel(id: string): string {
  return skills.find((skill) => skill.id === id)?.label ?? id;
}

export function domainLabel(id: DomainId | string): string {
  return communities.find((community) => community.id === id)?.shortName ?? id;
}
